version: "3.7"

networks: 
  rotten_mongo_network: 
    name: rotten_mongo_network 
    driver: bridge

volumes: 
  mongo_db_vol: {} 

services: 
  mongo_db: 
    image: mongo 
    container_name: mongo_db 
    networks: 
      - rotten_mongo_network 
    volumes: 
      - ./mongo_db_vol:/data/db 
    environment: 
      MONGO_INITDB_ROOT_USERNAME: root 
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
     - 27017:27017

  rotten-potatoes: 
    image: barbadockerlab/rotten-potatoes   
    build:  
      context: ./
      dockerfile: Dockerfile 
    container_name: rotten-potatoes 
    depends_on:  
      - mongo_db 
    networks: 
      - rotten_mongo_network
    ports: 
      - "5000:5000" 
    environment: 
      MONGODB_DB: admin
      MONGODB_HOST: mongo_db
      MONGODB_PORT: 27017
      MONGODB_USERNAME: root 
      MONGODB_PASSWORD: root

  mongo-express:
    image: mongo-express:1.0.0-alpha.4
    container_name: mongo-express
    environment:
      - ME_CONFIG_BASICAUTH_USERNAME=root
      - ME_CONFIG_BASICAUTH_PASSWORD=root
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=root
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_SERVER=mongo_db

    depends_on:  
     - mongo_db 

    ports:
      - "8081:8081"
    networks: 
      - rotten_mongo_network